name: '"Delete S3 Objects" Action for Github Actions'
description: Remove objects from a versioned or unversioned AWS S3 bucket.
inputs:
  bucket:
    description: S3 bucket to remove objects from.
    required: true
  prefix:
    description: |
      Use this input to select only those keys that begin with the specified
      prefix. If this input is left blank, all objects will be removed from the
      bucket.
    required: false
    default: ''
  allowEmptyPrefix:
    description: |
      When set to false, causes this action to throw an error when the `prefix`
      is empty. This prevents buckets from being accidentally wiped out if
      your action is misconfigured.
    required: false
    default: 'true'
outputs: {}
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: red
  icon: trash-2
